// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaA53z57qGL7r8I14LNoZ5fGl6rT1ei64',
    appId: '1:88501148935:web:06fcffdd8c0bfaeefcb9a2',
    messagingSenderId: '88501148935',
    projectId: 'magic-checks',
    authDomain: 'magic-checks.firebaseapp.com',
    storageBucket: 'magic-checks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0w7Gx9Z1QaFPrjvfJ41NaE5yCiq8juBc',
    appId: '1:88501148935:android:04c52298feb3961dfcb9a2',
    messagingSenderId: '88501148935',
    projectId: 'magic-checks',
    storageBucket: 'magic-checks.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnC3EwvNm08b4RcdsuLExun7JeugfayF0',
    appId: '1:88501148935:ios:1829ba96b0a498c6fcb9a2',
    messagingSenderId: '88501148935',
    projectId: 'magic-checks',
    storageBucket: 'magic-checks.firebasestorage.app',
    iosBundleId: 'com.example.magicChecks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaA53z57qGL7r8I14LNoZ5fGl6rT1ei64',
    appId: '1:88501148935:web:f206bda3f7d647bffcb9a2',
    messagingSenderId: '88501148935',
    projectId: 'magic-checks',
    authDomain: 'magic-checks.firebaseapp.com',
    storageBucket: 'magic-checks.firebasestorage.app',
  );
}
